<?php
/**
 * @file   : DateHelperTest.php
 * @time   : 10:45
 * @date   : 2021/9/10
 * @mail   : 9727005@qq.com
 * @creator: ShanDong Xiedali
 * @company: HiLand & RainyTop
 */

namespace Hiland\Test\data;

use DateTime;
use DateTimeZone;
use Exception;
use Hiland\Data\DateHelper;
use PHPUnit\Framework\TestCase;

class DateHelperTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        date_default_timezone_set("Asia/Shanghai");
    }

    public function testGetInterval(): void
    {
        $startValue = new DateTime("2021-09-10");
        $endValue   = new DateTime("2021-10-10");

        $actual = null;
        try {
            $actual = DateHelper::getInterval($startValue, $endValue);
        } catch (Exception $e) {
        }
        // dump($actual);
        self::assertEquals(0, $actual->invert);
        /**
         * ════════════════════════
         */
        $startValue = new DateTime("2021-09-10");
        $endValue   = new DateTime("2021-8-10");

        $actual = null;
        try {
            $actual = DateHelper::getInterval($startValue, $endValue);
        } catch (Exception $e) {
        }
        self::assertEquals(1, $actual->invert);
    }

    /**
     *
     */
    public function testGetDateTime(): void
    {
        $timespan = 2145888000;
        $actual   = "";
        try {
            $actual = DateHelper::getDateTime($timespan);
        } catch (Exception $e) {
        }
        $expected = new DateTime("2038-1-1 0:0:0");
        self::assertEquals($expected, $actual);

        $timespan = 2145888002;
        try {
            $actual = DateHelper::getDateTime($timespan);
        } catch (Exception $e) {
        }
        $expected = new DateTime("2038-1-1 0:0:2");
        self::assertEquals($expected, $actual);
    }


    public function testParseDateTimeSafely(): void
    {
        $dateString = "";
        $actual     = DateHelper::parseDateTimeSafely($dateString);
        self::assertFalse($actual);

        $dateString = 2145888000;
        $actual     = DateHelper::parseDateTimeSafely($dateString);
        $expected   = new DateTime("2038-1-1 0:0:0");
        self::assertEquals($expected, $actual);
    }

    public function testGetTimeZone(): void
    {
        $actual = DateHelper::getTimeZoneString();
        $expect = "Asia/Shanghai";
        self::assertEquals($expect, $actual);

        $actual = DateHelper::getTimeZoneObject();
        $expect = new DateTimeZone("Asia/Shanghai");
        self::assertEquals($expect, $actual);
    }

    public function testSetTimeZone(): void
    {
        DateHelper::setTimeZone("Asia/Tokyo");
        $actual = DateHelper::getTimeZoneString();
        $expect = "Asia/Tokyo";
        self::assertEquals($expect, $actual);

        $actual = DateHelper::getTimeZoneObject();
        $expect = new DateTimeZone("Asia/Tokyo");
        self::assertEquals($expect, $actual);
    }

    // public function testFormat()
    // {
    //
    // }
    // public function testAddInterval()
    // {
    //
    // }
    // public function testGetTimestamp()
    // {
    //
    // }
}
